# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE car;' -U postgres
  - psql -f part_3_001/2a_hbmxml/src/main/resources/create.sql car postgres
  - psql -c 'CREATE DATABASE avito;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуmailto:youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - mailto:mail-kochetkov@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always